name: telco_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==3.4.0
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - numpy==1.26.4
      - matplotlib==3.8.0
