name: CI - MLflow Project (pip / --no-conda)

on:
  push:
    paths:
      - 'MLProject/**'
      - 'telco_preprocessing/**'
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project (no conda)
        env:
          MLFLOW_TRACKING_URI: file:///${{ github.workspace }}/mlruns
        run: |
          mlflow --version
          mlflow run MLProject -P data_path=telco_preprocessing --no-conda

      - name: Upload MLflow artifacts (mlruns/)
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/